name: Playwright-Framework CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    name: Run Playwright Tests
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # 3. Install dependencies
      - name: Install dependencies from package-lock.json
        run: npm ci

      # 4. Run TypeScript compilation check
      - name: Check TypeScript compilation
        run: npm run tsc

      # 5. Run formatting and linting checks (do not fail on errors)
      - name: Check formatting with Prettier
        run: |
          npm run format:check || echo "Prettier check failed, please fix it... "

      - name: Run linting check with eslint
        run: |
          npm run lint || echo "Linting failed, please fix it... "

      # 6. Install Playwright browsers
      - name: Install Playwright browsers
        run: npm run install:browsers

      # 7. Run Playwright tests # customize as needed
      - name: Run Playwright Functional Tests
        run: npm run test:default
        continue-on-error: true

      # 8. Run Accessibility Tests
      - name: Run Accessibility Tests
        run: |
          mkdir -p accessibility-report
          REPORT_DIR=accessibility-report npm run test:accessibility
        continue-on-error: true

      # 9. Run Visual Tests
      - name: Run Visual Tests
        run: npm run test:visual
        continue-on-error: true

      # 10. Upload Accessibility Reports as Artifact
      - name: Upload Accessibility Reports
        uses: actions/upload-artifact@v3
        if: success() || failure()
        with:
          name: accessibility-report
          path: accessibility-report

      # 11. Generate and Upload Allure Report
      - name: Generate Allure Report
        run: |
          npx allure generate allure-results --clean -o allure-report
        if: always()

      - name: Upload Allure Report as Artifact
        if: success() || failure()
        uses: actions/upload-artifact@v3
        with:
          name: allure-report
          path: allure-report
