name: Playwright-Framework CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    name: Run Playwright Tests
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # 3. Install dependencies
      - name: Install dependencies from package-lock.json
        run: npm ci

      # 4. Run TypeScript compilation check
      - name: Check TypeScript compilation
        run: npm run tsc

      # 5. Run formatting and linting checks (do not fail on errors)
      - name: Check formatting with Prettier
        run: |
          npm run format:check || echo "Prettier check failed, please fix it... "

      - name: Run linting check with eslint
        run: |
          npm run lint || echo "Linting failed, please fix it... "

      # 6. Install Playwright browsers
      - name: Install Playwright browsers
        run: npm run install:browsers

      # 7. Run Playwright tests # customize as needed
      - name: Run Playwright Functional Tests
        run: npm run test:default-ci
        continue-on-error: true

      # 8. Run Accessibility Tests
      - name: Run Accessibility Tests
        run: |
          mkdir -p accessibility-report
          REPORT_DIR=accessibility-report npm run test:accessibility
        continue-on-error: true

      # 9. Run Visual Tests
      - name: Run Visual Tests
        run: npm run test:visual
        continue-on-error: true

      # 10. Generate Allure Report
      - name: Generate Allure Report
        run: |
          npx allure generate allure-results --single-file --clean -o allure-report
        if: always()

      # 11. Upload Artifact

      - name: Upload visual test snapshots
        uses: actions/upload-artifact@v4
        with:
          name: visual-test-snapshots
          path: src/tests/visual/**/visual.*.spec.ts-snapshots/
          overwrite: true
          if-no-files-found:: warn

      - name: Upload Accessibility Reports
        uses: actions/upload-artifact@v4
        if: success() || failure()
        with:
          name: accessibility-report
          path: accessibility-report
          overwrite: true
          if-no-files-found:: warn

      - name: Upload Allure Report as Artifact
        if: success() || failure()
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: allure-report
          overwrite: true
          if-no-files-found:: warn

       # 12. Deploy Reports to gh-page-reports Branch
      - name: Deploy Reports to GitHub Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: reports
          publish_branch: gh-pages
        env:
          PUBLISH_DIRS: |
            allure-report:/allure-report
            accessibility-report:/accessibility-report